baseurl = "https://wbaer.net"
languageCode = "en-us"
Title = "Bill Bär ('bɛər)"
copyright = "&copy; 2020 Bill Bär"

# Parameters

[params]
  description = "Bill Baer is a Senior Technical Product Manager and Microsoft Certified Master for SharePoint in the SharePoint & OneDrive product group in Redmond, Washington; having previously worked at Hewlett-Packard Bill Baer has a proven background in infrastructure engineering and enterprise deployments of SharePoint Products and Technologies."
  paginate = 3

  twitter = "@williambaer"
  github = "wbaer"
  #gitlab = "Your GitLab username"
  linkedin = "billbaer"
  
  author = "Bill Bär"
  authorwebsite = "wbaer.net"
  subtitle = "Bill Bär is a Senior Product Manager for Microsoft Search, Assistant, and Intelligence at Microsoft in Redmond, Washington"
  
[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2
    
[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10