baseurl = "https://wbaer.net"
languageCode = "en-us"
Title = "Bill Bär ('bɛər)"
copyright = "&copy; 2020 Bill Bär"

# Outputs

[outputs]
  section = ["JSON", "HTML"]

# Parameters

[params]
  paginate = 5

  twitter = "@williambaer"
  github = "wbaer"
  linkedin = "billbaer"
  
[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2
    
[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10