baseurl = "https://wbaer.net"
languageCode = "en-us"
Title = "Bill Bär ('bɛər)"
copyright = "&copy; 2020 Bill Bär"

# Parameters

[params]
  description = "Bill Baer is a Senior Technical Product Manager and Microsoft Certified Master for SharePoint in the SharePoint & OneDrive product group in Redmond, Washington; having previously worked at Hewlett-Packard Bill Baer has a proven background in infrastructure engineering and enterprise deployments of SharePoint Products and Technologies."
  paginate = 2

  twitter = "@williambaer"
  github = "wbaer"
  #gitlab = "Your GitLab username"
  linkedin = "billbaer"
  
  author = "Bill Bär"
  authorwebsite = "wbaer.net"
  subtitle = "Bill Bär is a Senior Product Manager for Microsoft Search, Assistant, and Intelligence at Microsoft in Redmond, Washington"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"