baseurl = "https://wbaer.net"
languageCode = "en-us"
Title = "Bill Bär ('bɛər)"
copyright = "&copy; 2020 Bill Bär"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
posts = "/:year/:month/:slug/"
archm = "/:year/:month/"
archy = "/:year/"

# Outputs

[outputs]
home = ["HTML","RSS","Lunr"]
  
[outputFormats.Lunr]
baseName = "lunr"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.lunr]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

# Parameters

[params]
  paginate = 5

  twitter = "@williambaer"
  github = "wbaer"
  linkedin = "billbaer"
  
[taxonomies]
  category = "categories"
  tag = "tags"
  
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
    
[[menu.main]]
    name = "Archives"
    url = "/archive"
    weight = 3
    
[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

[[menu.horizontal]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.horizontal]]
  name = "About"
  url = "/about"
  weight = 2
  
[[menu.horizontal]]
  name = "Archives"
  url = "/archives"
  weight = 3

[[menu.horizontal]]
  name = "Tags"
  url = "/tags"
  weight = 4
    
[related]
  includeNewer = false
  threshold = 80
  toLower = false
    
  [[related.indices]]
    name = "keywords"
    weight = 150
    
  [[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
    
  [[related.indices]]
    name  = "tags"
    weight = 100
    
  [[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2017"